### ISSUE TITLE
Search not working in 1.2.0 in environments without web access

### ISSUE THREAD

**Issue by tmct** [readthedocs/sphinx_rtd_theme#1434]
### Problem

Hi,

When I upgrade to 1.2.0, the "search" feature stops working in airgapped environments. When a search is initiated, it "spins" but does not finish.

Also observed:
1) on load, the webpage tries to access https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js upon load, and this fails in environments with no internet access, as expected
2) "Uncaught ReferenceError: jQuery is not defined" happens when you initiate a search

### Reproducible Project

Cannot share, sorry - but it shouldn't matter

#### Error Logs/Results

See above

#### Expected Results

Search completes as expected

### Environment Info

- Python Version: 3.8 and 3.9
- Sphinx Version: 6.1.3
- RTD Theme Version: 1.2.0

**Comment by benjaoming** [comment]
@tmct we forced the version of `sphinxcontrib-jquery` to exclude `3.0.0` because there were incoming reports that jQuery wasn't loaded in local builds because of an SRI integrity check. See: https://github.com/readthedocs/sphinx_rtd_theme/issues/1420

If you can force-feed pip `sphinxcontrib-jquery==3.0.0`, you should be able to serve an airgapped build.

This will be finally fixed by a new version of sphinxcontrib-jquery: https://github.com/sphinx-contrib/jquery/pull/14

**Comment by tmct** [comment]
Thanks very much! I'll keep an eye on that `sphinxcontrib-jquery` change.

**Comment by gherceg** [comment]
@benjaoming we are experiencing a similar issue, but after upgrading `sphinxcontrib-jquery` to 4.1 (with `sphinx==6.1.3` and `sphinx-rtd-theme==1.2`), the "Uncaught ReferenceError: jQuery is not defined" error still occurs when using the search bar.

**Comment by benjaoming** [comment]
@gherceg thanks for the feedback!! do you have a build log, a link to the documentation and/or a git repo that I can have a look at?

**Comment by gherceg** [comment]
Yeah of course. [commcare-hq](https://github.com/dimagi/commcare-hq) is the repository, and the docs are [here](https://commcare-hq.readthedocs.io/), but notably that docs build is still running `sphinxcontrib-jquery==2.0.0`, with the same versions for sphinx and sphinx-rtd-theme mentioned above.

With `sphinxcontrib-jquery==4.1`, I ran `sphinx-build -M html . _build 2>&1 1>/dev/null | tee sphinx-build.log` which has a lot of `django.core.exceptions.AppRegistryNotReady` warnings that make it pretty verbose so apologies for that.
[sphinx-build.log](https://github.com/readthedocs/sphinx_rtd_theme/files/10995234/sphinx-build.log)

**Comment by benjaoming** [comment]
@gherceg ah! I recognize this issue. We removed it from the injected default configuration, but very old instructions had `html_theme_path`. It switches off the theme's ability to automatically enable the sphinxcontrib-jquery extension, so you either have to enable the extension manually or remove `html_theme_path` from `conf.py`. Since it's unnecessary, you can just remove it as suggested in https://github.com/dimagi/commcare-hq/pull/32760 :+1:

**Comment by LGouellec** [comment]
Try `https://lgouellec.github.io/streamiz/index.html`, Search "Branch" in the search tab, it "spins" but does not finish. Same for any other words.

**Comment by humitos** [comment]
@LGouellec what version of the theme are you using? what's the version of Sphinx itself? Can you try using the latest version of the theme?

**Comment by LGouellec** [comment]
I tried the last one `2.0.0`, but without effects

https://github.com/LGouellec/streamiz/blob/master/.github/workflows/gh-pages.yml

**Comment by humitos** [comment]
@LGouellec the error in the browser's console says: `Uncaught ReferenceError: jQuery is not defined`. So, I think `2.0.0` is not being installed correctly. What's the output of the build process? Is this one https://github.com/LGouellec/streamiz/actions/runs/10357412706/job/28669387744?

**Comment by LGouellec** [comment]
@humitos Yes it's this one, full raw logs available here : https://productionresultssa16.blob.core.windows.net/actions-results/30612698-4096-4adc-bf39-e74cb39f2037/workflow-job-run-ef53817e-be1e-5b9f-8d47-e63fd9dfbe04/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-13T22%3A56%3A16Z&sig=Jb7RxTBKatInP8gQ10cAPBnX%2FACCLlw80n1z7RpFuM8%3D&ske=2024-08-14T07%3A52%3A48Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-13T19%3A52%3A48Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-13T22%3A46%3A11Z&sv=2024-05-04

**Comment by LGouellec** [comment]
[0_build-and-deploy.txt](https://github.com/user-attachments/files/16606251/0_build-and-deploy.txt)

**Comment by humitos** [comment]
I notice that you don't have the theme added as an extension in https://github.com/LGouellec/streamiz/blob/master/docs/conf.py#L33 as our documentation mentions https://sphinx-rtd-theme.readthedocs.io/en/stable/installing.html. Can you try that?

**Comment by LGouellec** [comment]
@humitos , 

I have added the extension and now it works ! Thank you for your support.
